
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: janifer
  password: B019cj9@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

